{% set version = "1.19.0" %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: d1c782a54b9ebcdc1dedf8356a25ee11e11099a664a7d9413fdd3742138fa140

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
