{% set version = "1.17.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: 3dcd86c12e96ab5808d5c9f3cec0fcc04192a87833ff009063c4a491d5487b58

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
