{% set version = "1.18.0" %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: fea7b92922117ed04b9c84bb9998026264346768804f66baa40743c5528bed6b

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
