{% set version = "1.13.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hyperfine
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v{{ version }}.tar.gz
  sha256: 6e57c8e51962dd24a283ab46dde6fe306da772f4ef9bad86f8c89ac3a499c87e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - hyperfine --help

about:
  home: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
