schema_version: 1

context:
  version: "2.0.0"

package:
  name: hyperfine
  version: ${{ version }}

source:
  url: https://github.com/sharkdp/hyperfine/archive/v${{ version }}.tar.gz
  sha256: f4b71df3c78e4cf752ca6fb6ebc4b025f7ea6a5ca5c48fea75f8a1fdb4c7d721

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - package_contents:
      bin:
        - hyperfine
  - script:
      - hyperfine --help

about:
  homepage: https://github.com/sharkdp/hyperfine
  repository: https://github.com/sharkdp/hyperfine
  license: MIT
  license_family: MIT
  summary: A command-line benchmarking tool
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
