travis:
  secure:
    BINSTAR_TOKEN: kQFeF9/fxziLljgvLyPFUmt5ruehAf4UiN6Nn5H5e3FB+mrrxd2xEC9Zc5w6Z+B2bAg9AM+1JrgWDRd+DhQIy381Rff/8ayG3glywyaCYdyiXPlDiOtTxLzbaHtzgVCjdxfNcb6o7zZdY0FAbRNvz8SlOSplZCBrQxrPOD4yfx7gPodGowUMeTZ5jzqToHWyQF4F8NjdgQExaLS9IkryhBYZXM7BIgF2ntEZgmfE1Fe+7StCsDV0loiiqFmU2FLk5r1exB1pYpBD9biV+St0YQ8k6fPlauWiC81+si+TJvwBnsc4hBKL5ufVTHI8jncubctgi3lqUMB+PjmXTeTx2Q5v6mWOUZ/zVoOHob1jfFqLfd33sl493kTZUb7U2SE4KzvJH8YQkXTKVcndvCRBVSs7Esu6tEk70Rn83DbQFIGT7sFR5Fp61CjbUskdcsRQoePOwjyU+9UJ5zjOyddVFTt4KKxJRE7J35C1bxdBMvqMtrAqvqpx0VJvZDd+uuhaRkr02MCD+3FbykW4u115O2Tsa7mWln+lJ3qLTyUHgttMZyS8v5AOxg48BEmuEmEOJu4ZrfI9rJZc8P/lwJ9nogDzJUdGi81IjQD5JUvtNoQM4+qty3FQRPjuPCBATK40rJ0EjtncG5ppbY+STjWJLM+qrbrLXT+4Whs5vZN56Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
